# config-tu-luyen.yml

tuvi:
  canh_gioi:
    - name: "Luyện Thể"
      exp_required: 100
      buffs:
        health: 0
        damage: 0
        speed: 0
    - name: "Luyện Khí"
      exp_required: 300
      buffs:
        health: 2
        damage: 1
        speed: 0
    - name: "Trúc Cơ"
      exp_required: 800
      buffs:
        health: 4
        damage: 2
        speed: 1
    - name: "Kim Đan"
      exp_required: 1500
      buffs:
        health: 6
        damage: 4
        speed: 1
    - name: "Nguyên Anh"
      exp_required: 3000
      buffs:
        health: 8
        damage: 6
        speed: 1
    - name: "Hóa Thần"
      exp_required: 6000
      buffs:
        health: 10
        damage: 8
        speed: 2
    - name: "Phân Thần"
      exp_required: 10000
      buffs:
        health: 14
        damage: 10
        speed: 2
    - name: "Đại Thừa"
      exp_required: 16000
      buffs:
        health: 18
        damage: 12
        speed: 3
    - name: "Độ Kiếp"
      exp_required: 25000
      buffs:
        health: 25
        damage: 15
        speed: 4
    - name: "Phi Thăng"
      exp_required: 40000
      buffs:
        health: 30
        damage: 20
        speed: 5

tuluyen:
  base_exp_per_second: 1
  dan_boost:
    tieu: 0.5
    trung: 1.0
    dai: 2.0